### ISSUE TITLE
make failed on CentOS 5.11

### ISSUE THREAD

**Issue by meteor5118** [tbricks/tbstack#3]
[root@localhost tbstack]# make
gcc -O2 -D_XOPEN_SOURCE -D_GNU_SOURCE   -c -o src/unwind.o src/unwind.c
src/unwind.c: In function ‘dw_get_value’:
src/unwind.c:39:16: error: ‘DW_EH_PE_omit’ undeclared (first use in this function)
     if (enc == DW_EH_PE_omit) {
                ^
src/unwind.c:39:16: note: each undeclared identifier is reported only once for each function it appears in
src/unwind.c:44:16: error: ‘DW_EH_PE_absptr’ undeclared (first use in this function)
     if (enc == DW_EH_PE_absptr) {
                ^
src/unwind.c:51:10: error: ‘DW_EH_PE_udata2’ undeclared (first use in this function)
     case DW_EH_PE_udata2:
          ^
src/unwind.c:56:10: error: ‘DW_EH_PE_sdata2’ undeclared (first use in this function)
     case DW_EH_PE_sdata2:
          ^
src/unwind.c:61:10: error: ‘DW_EH_PE_udata4’ undeclared (first use in this function)
     case DW_EH_PE_udata4:
          ^
src/unwind.c:66:10: error: ‘DW_EH_PE_sdata4’ undeclared (first use in this function)
     case DW_EH_PE_sdata4:
          ^
src/unwind.c:71:10: error: ‘DW_EH_PE_udata8’ undeclared (first use in this function)
     case DW_EH_PE_udata8:
          ^
src/unwind.c:76:10: error: ‘DW_EH_PE_sdata8’ undeclared (first use in this function)
     case DW_EH_PE_sdata8:
          ^
src/unwind.c:92:10: error: ‘DW_EH_PE_pcrel’ undeclared (first use in this function)
     case DW_EH_PE_pcrel:
          ^
make: **\* [src/unwind.o] Error 1

**Comment by v-nikulichev** [comment]
Could you please run this command?

```
gcc -D_XOPEN_SOURCE -D_GNU_SOURCE src/unwind.c -E | grep dwarf.h
```

Which package (and version) does provide this file?
