### ISSUE TITLE
attach: Operation not permitted

### ISSUE THREAD

**Issue by killerkalamari** [tbricks/tbstack#32]
tbstack was working fine for a while, but then I started to get output that did not contain a backtrace:

```
segfault signal in version a14c0abc:
attach: Operation not permitted
detach: No such process
-----------------------  summary  --------------------------
 time the process was frozen: 0ms 41us
 sleep count: 0
 total bytes copied: 0x0 (0K)
```

I was able to get tbstack working again by issuing the following commands (note: setuid root can pose a security risk):
```
chown 0:0 tbstack
chmod 4755 tbstack
```

Is there a way to resolve this without setuid root?

Ubuntu 16.04 LTS, kernel 4.15.0-106-generic, tbstack 1.0

**Comment by antonsmyk** [comment]
It must be that you have ptrace disabled on your Ubuntu 16.04 system. Please have a look at https://wiki.ubuntu.com/Security/Features#ptrace and  https://www.kernel.org/doc/html/latest/admin-guide/LSM/Yama.html

I've installed a test Ubuntu 16.04 virtual machine, and indeed, out of the box it has ptrace disabled:

```
$ cat /proc/sys/kernel/yama/ptrace_scope
1
```

And it fails as in your example:
```
$ sleep 20 &
[1] 1243

$ ./tbstack-build/tbstack 1243
attach: Operation not permitted
detach: No such process
-----------------------  summary  --------------------------
 time the process was frozen: 0ms 95us
 sleep count: 0
 total bytes copied: 0x0 (0K)
```


Enable ptrace with something like this:
```
$ sudo sh -c 'echo 0 > /proc/sys/kernel/yama/ptrace_scope'
```


And now it works:
```
$ sleep 20 &
[1] 1317
$ ./tbstack-build/tbstack 1317
--------------------  thread 1 (1317)  --------------------
 00007f6e78e4d370  nanosleep + 0x10
 00000000004040bf  ?? (sleep)
 0000000000403f18  ?? (sleep)
 000000000040169a  ?? (sleep)
 00007f6e78da1840  __libc_start_main + 0xf0
 0000000000401789  ?? (sleep)
-----------------------  summary  --------------------------
 time the process was frozen: 0ms 275us
 sleep count: 0
 total bytes copied: 0x2000 (8K)
```

You can permanently enable ptrace with custom sysctl config entry as shown in https://askubuntu.com/a/41656:

```
$ echo "kernel.yama.ptrace_scope = 0" | sudo tee /etc/sysctl.d/99-ptrace.conf
```
